{% set name = "tensorboardX" %}
{% set version = "1.2" %}
{% set sha256 = "711ad14bc36bb563474cbb2219fef0a466c9a822e7cf2bf1e2ca11a7dbdc8224" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - protobuf >=0.3.2
    - six

test:
  imports:
    - tensorboardX
    - tensorboardX.crc32c
    - tensorboardX.embedding
    - tensorboardX.event_file_writer
    - tensorboardX.graph
    - tensorboardX.graph_onnx
    - tensorboardX.record_writer
    - tensorboardX.summary
    - tensorboardX.writer
    - tensorboardX.x2num

about:
  home: https://github.com/lanpa/tensorboard-pytorch
  license: MIT
  license_family: MIT
  summary: tensorboard for pytorch

  description: |
    Write tensorboard events from PyTorch (and Chainer, MXNet, NumPy, ...)
  doc_url: http://tensorboard-pytorch.readthedocs.io/en/latest/
  dev_url: https://github.com/lanpa/tensorboard-pytorch

extra:
  recipe-maintainers:
    - mdraw
    - lanpa
