{% set name = "tensorboardX" %}
{% set version = "2.5.1" %}
{% set sha256 = "eed6b8109d200e9c1529abe8a9f755894a5db9c82166bcaaf80c41a48398c6fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lanpa/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - protobuf >=3.8.0,<=3.20.1
    - six

test:
  imports:
    - tensorboardX
    - tensorboardX.crc32c
    - tensorboardX.embedding
    - tensorboardX.event_file_writer
    - tensorboardX.onnx_graph
    - tensorboardX.record_writer
    - tensorboardX.summary
    - tensorboardX.writer
    - tensorboardX.x2num

about:
  home: https://github.com/lanpa/tensorboardx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: tensorboard for pytorch

  description: |
    Write tensorboard events from PyTorch (and Chainer, MXNet, NumPy, ...)
  doc_url: https://tensorboardx.readthedocs.io/en/latest/
  dev_url: https://github.com/lanpa/tensorboardx

extra:
  recipe-maintainers:
    - mdraw
    - lanpa
